---
title: "Shiny Rmarkdown"
author: "Julianna Renzi"
date: "1/26/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r flippers, echo = FALSE}
# create interactive panel

inputPanel(
  
  selectInput(inputId = "pick_spp",
              label = "Pick your penguin species",
              choices = c("Adélie" = "Adelie", "Cool chinstrap" = "Chinstrap", "Gentoo"), selected = "Gentoo"), # First widget is a drop down. selected is what is automatically shown
  
  sliderInput(inputId = "pt_size",
              label = "Set your point size:",
              min = 1,
              max = 10,
              step = 0.5,
              value = 5) # value is starting value
  
  
  
)


# now create a reactive subset based on user selection
penguin_set <- reactive({
  penguins %>% 
    filter(species == input$pick_spp)
}) # stores it but still need to make a plot

renderPlot({
  ggplot(data = penguin_set(), aes(x = flipper_length_mm, y = body_mass_g)) + 
    geom_point(size = input$pt_size)
})

# to publish, click the publish button and then set it up online and can then share the website with folks
```

